# Generated by Django 3.2.8 on 2021-10-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_alter_cart_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_Item',
            new_name='CartItem',
        ),
        migrations.RenameModel(
            old_name='Order_Item',
            new_name='OrderItem',
        ),
    ]
