# Generated by Django 3.2.8 on 2021-10-21 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_auto_20211020_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='films', to='movies_app.genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='featured_film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='movies_app.film'),
        ),
    ]
