# Generated by Django 3.2.8 on 2021-10-23 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0004_auto_20211021_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={},
        ),
        migrations.AlterField(
            model_name='order_item',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to='movies_app.film'),
        ),
    ]
